### ISSUE TITLE
Switch CI to CircleCI

### ISSUE THREAD

**Issue by koppor** [raphink/nowidow#3]
Travis builds are broken somehow. I am using [koppor/texlive](https://hub.docker.com/r/koppor/texlive/) for my builds of [the official LNI template](https://github.com/gi-ev/LNI) or my [scientific-thesis-template](http://latextemplates.github.io/scientific-thesis-template/).

The file `.circleci/config.yml` for this repository would render as follows:

```
version: 2
jobs:
   build:
     docker:
       - image: koppor/texlive
     steps:
       - checkout
       - run: make nowidow.pdf
       - run: bundle update
       - run: make check
```
